project:
  type: book
  output-dir: docs

book:
  title: "CORN318 Marine Pollution and Ecotoxicology"
  author: "Michael Hunt"
  date: "1/29/2026"
  chapters:
    - index.qmd
    - climate_change_impacts.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

